version: '2'
services:
    expense-hub-ui:
        container_name: expense-hub-ui
        image: vilellaj/expense-hub-ui
        ports:
            - '80:80'
        depends_on:
            - "expense-hub-service"
    expense-hub-service:
        container_name: expense-hub-service
        image: vilellaj/expense-hub-service
        ports:
            - '3000:80'